#!/usr/bin/python3

from sys import argv, stderr
import subprocess
from concurrent.futures import ThreadPoolExecutor

# Check for proper input
if len(argv) < 3:
    print(f"Usage: {argv[0]} [path of hostfile] [file to copy]", file=stderr)
    exit(1)

if not argv[2].startswith("/"):
    print("File to be copied is not an absolute path.", file=stderr)
    exit(2)

# Transfer file

current_ip = subprocess.run(["hostname", "-I"], stdout=subprocess.PIPE).stdout.decode('utf-8').strip()

def transfer(ip):
    returncode = subprocess.run(["scp", argv[2], f"{ip}:{argv[2]}"]).returncode
    print("Exit code for", ip, "-", returncode)

with open(argv[1], 'r') as f:
    with ThreadPoolExecutor() as executor:
        results = [executor.submit(transfer, ip) for ip in map(str.strip, f) if ip != current_ip]
