#!/usr/bin/python3

from sys import argv, stderr
from os.path import abspath
import subprocess
from concurrent.futures import ThreadPoolExecutor

# Check for proper input
if len(argv) < 3:
    print(f"Usage: {argv[0]} [path of hostfile] [file to copy]", file=stderr)
    exit(1)

file = argv[2]

if not file.startswith("/"):
    file = abspath(file)
    print("File to be copied is not an absolute path. Changing to", file)

# Transfer file

current_ip = subprocess.run(["hostname", "-I"], stdout=subprocess.PIPE).stdout.decode('utf-8').strip()

def transfer(ip):
    returncode = subprocess.run(["scp", file, f"{ip}:{file}"]).returncode
    print("Exit code for", ip, "-", returncode)

with open(argv[1], 'r') as f:
    with ThreadPoolExecutor() as executor:
        results = [executor.submit(transfer, ip) for ip in map(str.strip, f) if ip != current_ip]
